from datetime import UTC, datetime


def utcnow() -> datetime:
    """Centralized timezone-aware current UTC time.

    The WHY:
        In a multi-tenant RAG system with "Temporal Memory" (Versioned
        Documents), inconsistent timestamps (mixing local time with
        UTC) are a major source of bugs. This utility ensures that
        every timestamp generated by the platform (for ingestion,
        audit logs, or versioning) is a standardized, timezone-aware
        UTC object.
    """
    return datetime.now(UTC)
